version: "3.4"

volumes:
  db-data:

services:
  database:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - db-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PW}
      - ASPNETCORE_ENVIRONMENT=Development